// Auto-generated by scripts/generate-blog-meta.ts
export const blogMeta = {
  "why-i-jailbroke-my-kindle-and-what-i-discovered": {
    "updatedAt": "2026-03-31T18:31:26.012Z"
  },
  "wsl-cross-boundary-io": {
    "updatedAt": "2026-03-31T19:00:20.653Z"
  },
  "systems-to-fullstack": {
    "updatedAt": "2026-03-31T11:37:59.740Z"
  }
} as const
