// Auto-generated by scripts/generate-blog-meta.ts
export const blogMeta = {
  "why-i-use-wsl": {
    "updatedAt": "2026-04-03T00:50:20.661Z"
  },
  "wsl-cross-boundary-io": {
    "updatedAt": "2026-04-03T00:32:58.686Z"
  },
  "why-i-jailbroke-my-kindle-and-what-i-discovered": {
    "updatedAt": "2026-04-03T00:32:58.686Z"
  },
  "koreader-orientation-highlight-refresh": {
    "updatedAt": "2026-04-03T00:32:58.686Z"
  }
} as const
