import { readdir, stat, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'

const BLOG_DIR = resolve('src/content/blog')
const OUTPUT = resolve('src/content/blog.meta.ts')

async function main() {
  const entries = await readdir(BLOG_DIR, { withFileTypes: true })
  const meta: Record<string, { updatedAt: string }> = {}

  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith('.md')) {
      continue
    }

    const slug = entry.name.replace(/\.md$/, '')
    const fullPath = resolve(BLOG_DIR, entry.name)
    const fileStat = await stat(fullPath)
    meta[slug] = {
      updatedAt: fileStat.mtime.toISOString(),
    }
  }

  const output = `// Auto-generated by scripts/generate-blog-meta.ts\nexport const blogMeta = ${JSON.stringify(
    meta,
    null,
    2,
  )} as const\n`

  await writeFile(OUTPUT, output, 'utf8')
  console.log(`Generated ${OUTPUT}`)
}

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error)
  console.error(message)
  process.exit(1)
})
